#!/usr/bin/env python3
"""D10-D publication pack: deterministic generator + fail-closed verifier.

Modes
-----
build      regenerate tables/ and figures/ from the ACCEPTED artifacts only
check      fail-closed: declared source hashes, generated bytes, map citations
hashcheck  fail-closed: every 64-hex token in this pack is a real hash

Policy: publication / communication over accepted D9-D evidence only. This
script reads accepted artifacts; it never writes to them, never re-runs any
study, and never touches the network.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import cast

PACK = Path(__file__).resolve().parents[1]
ROOT = PACK.parents[1]
REPRO = PACK / "reproducibility.json"
SOURCE_MAP = PACK / "RESULT-SOURCE-MAP.md"

TARGETS = ("primary", "secondary")
PERIODS = ("formation_dev", "validation", "historical_evaluation")
MODELS = (
    "model0_majority_baseline",
    "model1_market_only",
    "model2_text_only",
    "model3_market_text_combined",
)
RESULTS = "results/historical_text_v2"
PACK_SUFFIXES = (".md", ".json", ".csv", ".svg", ".py", ".yml")
HEX64 = re.compile(r"\b[0-9a-f]{64}\b")
HEX40 = re.compile(r"\b[0-9a-f]{40}\b")
ABBR = re.compile(r"\b([0-9a-f]{7,63})…")
ROW = re.compile(r"^\|\s*(C-\d+)\s*\|([^|]*)\|([^|]*)\|([^|]*)\|")
SELFTEST_FIXTURES = {hashlib.sha256(b"abc").hexdigest()}


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def load_repro() -> dict:
    return cast(dict, json.loads(REPRO.read_text(encoding="utf-8")))


def artifact_path(target: str, period: str) -> str:
    return f"{RESULTS}/sentiment_hist_text_v2_{target}_{period}.json"


def load_artifact(target: str, period: str) -> dict:
    return cast(dict, json.loads(
        (ROOT / artifact_path(target, period)).read_text(encoding="utf-8")))


def km(doc: dict) -> dict:
    return cast(dict, doc["result"]["key_metrics"])


def pm(doc: dict) -> dict:
    return cast(dict, doc["result"]["period_metrics"])


def cell(value: object) -> str:
    """Exact, deterministic cell: floats via repr, None as 'null'."""
    if value is None:
        return "null"
    if isinstance(value, float):
        return repr(value)
    return str(value)


def csv_bytes(header: list[str], rows: list[list[object]]) -> bytes:
    lines = [",".join(header)]
    for row in rows:
        lines.append(",".join(cell(v).replace(",", ";") for v in row))
    return ("\n".join(lines) + "\n").encode("utf-8")


def build_artifact_hashes(repro: dict) -> bytes:
    rows = []
    for src in repro["source_artifacts"]:
        path = ROOT / src["path"]
        measured = sha256_file(path)
        rows.append([src["path"], measured, path.stat().st_size, src["sha256"], src["role"]])
    header = ["path", "sha256_measured", "bytes", "sha256_declared", "role"]
    return csv_bytes(header, rows)


def build_period_metrics() -> bytes:
    header = [
        "period",
        "target",
        "model",
        "log_loss",
        "brier_score",
        "balanced_accuracy",
        "roc_auc",
        "accuracy",
        "samples",
    ]
    rows = []
    for period in PERIODS:
        for target in TARGETS:
            metrics = pm(load_artifact(target, period))
            for model in MODELS:
                m = metrics.get(model, {})
                rows.append(
                    [
                        period,
                        target,
                        model,
                        m.get("log_loss"),
                        m.get("brier_score"),
                        m.get("balanced_accuracy"),
                        m.get("roc_auc"),
                        m.get("accuracy"),
                        m.get("samples"),
                    ]
                )
    return csv_bytes(header, rows)


def build_target_comparison() -> bytes:
    header = [
        "period",
        "target",
        "model1_log_loss",
        "model3_log_loss",
        "delta_log_loss_model3_minus_model1",
        "ci_low_95",
        "ci_high_95",
        "ci_n_resamples",
        "delta_balanced_accuracy",
        "n_eval_rows",
        "n_train_rows",
        "n_unique_issuers_eval",
        "c_source",
        "historical_evaluation_label",
        "evaluation_block_label",
    ]
    rows = []
    for period in PERIODS:
        for target in TARGETS:
            doc = load_artifact(target, period)
            k = km(doc)
            ci = k["headline_bootstrap_delta_log_loss_ci95"]
            rows.append(
                [
                    period,
                    target,
                    k["model1_log_loss"],
                    k["model3_log_loss"],
                    k["headline_delta_log_loss_model3_minus_model1"],
                    ci["ci_low"],
                    ci["ci_high"],
                    ci["n_resamples"],
                    k["headline_delta_balanced_accuracy_model3_minus_model1"],
                    k["n_eval_rows"],
                    k["n_train_rows"],
                    k["n_unique_issuers_eval"],
                    doc.get("c_source", "null"),
                    doc.get("historical_evaluation_label", "null"),
                    k["evaluation_block_label"],
                ]
            )
    return csv_bytes(header, rows)


def build_figure() -> bytes:
    """Deterministic grouped bars: log loss per model, per target, 2025 block."""
    series = []
    for target in TARGETS:
        metrics = pm(load_artifact(target, "historical_evaluation"))
        series.append((target, [metrics[m]["log_loss"] for m in MODELS]))
    lo, hi = 0.685, 0.700
    w, h, pad = 760, 380, 60
    plot_h = h - 2 * pad
    bar_w, group_gap = 42, 150
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
        f'viewBox="0 0 {w} {h}" role="img" '
        f'aria-label="Log loss by model, 2025 historical evaluation">',
        f'<rect width="{w}" height="{h}" fill="#0f1115"/>',
        f'<text x="{pad}" y="28" fill="#e6e6e6" font-family="monospace" font-size="15">'
        "2025 HISTORICAL EVALUATION — log loss by model (lower is better)</text>",
    ]

    def y_of(value: float) -> float:
        frac = (hi - value) / (hi - lo)
        return pad + frac * plot_h

    parts.append(
        f'<line x1="{pad}" y1="{y_of(lo)}" x2="{w - pad}" y2="{y_of(lo)}" '
        'stroke="#3a3f4b"/>'
    )
    for gi, (target, values) in enumerate(series):
        x0 = pad + 40 + gi * group_gap
        parts.append(
            f'<text x="{x0}" y="{h - 24}" fill="#9aa4b2" font-family="monospace" '
            f'font-size="13">{target}</text>'
        )
        for mi, value in enumerate(values):
            x = x0 + mi * (bar_w + 6)
            y = y_of(value)
            colour = "#5b8def" if mi != 3 else "#e0674a"
            parts.append(
                f'<rect x="{x}" y="{y:.2f}" width="{bar_w}" height="{y_of(lo) - y:.2f}" '
                f'fill="{colour}"/>'
            )
            parts.append(
                f'<text x="{x}" y="{y - 6:.2f}" fill="#c9d1d9" font-family="monospace" '
                f'font-size="11">{value:.5f}</text>'
            )
            parts.append(
                f'<text x="{x}" y="{y_of(lo) + 16:.0f}" fill="#8b949e" font-family="monospace" '
                f'font-size="11">M{mi}</text>'
            )
    parts.append(
        f'<text x="{w - pad}" y="{h - 24}" fill="#8b949e" text-anchor="end" '
        'font-family="monospace" font-size="11">'
        "M0 baseline · M1 market · M2 text · M3 market+text (headline vs M1)</text>"
    )
    parts.append("</svg>")
    return ("\n".join(parts) + "\n").encode("utf-8")


def build() -> dict[str, bytes]:
    repro = load_repro()
    return {
        "tables/artifact-hashes.csv": build_artifact_hashes(repro),
        "tables/period-metrics.csv": build_period_metrics(),
        "tables/target-comparison.csv": build_target_comparison(),
        "figures/log-loss-comparison.svg": build_figure(),
    }


def check() -> int:
    repro = load_repro()
    failures: list[str] = []

    artifact_hashes = 0
    for src in repro["source_artifacts"]:
        path = ROOT / src["path"]
        if not path.is_file():
            failures.append(f"missing source artifact: {src['path']}")
            continue
        measured = sha256_file(path)
        if measured != src["sha256"]:
            failures.append(
                f"hash mismatch {src['path']}: "
                f"declared {src['sha256'][:12]}… measured {measured[:12]}…"
            )
            continue
        artifact_hashes += 1

    generated = build()
    for rel, expected in generated.items():
        path = PACK / rel
        if not path.is_file():
            failures.append(f"missing generated file: {rel}")
            continue
        actual = path.read_bytes()
        if actual != expected:
            failures.append(f"generated file not reproducible: {rel}")

    citations = 0
    for line in SOURCE_MAP.read_text(encoding="utf-8").splitlines():
        match = ROW.match(line)
        if not match:
            continue
        _, _claim, path_cell, sha_cell = match.groups()
        rel = path_cell.strip().strip("`")
        declared = sha_cell.strip().strip("`")
        target = ROOT / rel
        if not target.is_file():
            failures.append(f"citation {match.group(1)}: missing path {rel}")
            continue
        measured = sha256_file(target)
        if measured != declared:
            failures.append(f"citation {match.group(1)}: {rel} hash mismatch")
            continue
        citations += 1

    for problem in failures:
        print(f"FAIL {problem}")
    if failures:
        print(f"check FAILED: {len(failures)} problem(s)")
        return 1
    print(
        f"check OK: {artifact_hashes} declared artifact hashes verified, "
        f"{len(generated)} generated files byte-identical, {citations} map citations verified"
    )
    return 0


def hashcheck() -> int:
    repro = load_repro()
    known = set(SELFTEST_FIXTURES)
    for src in repro["source_artifacts"]:
        known.add(src["sha256"])
    for rel, data in build().items():
        known.add(sha256_bytes(data))
        disk = PACK / rel
        if disk.is_file():
            known.add(sha256_file(disk))


    git_shas = list(repro["accepted_evidence"]["git_shas"])
    external = list(repro["accepted_evidence"]["external_git_shas"])
    allowed_shas = set(git_shas) | set(external)
    failures: list[str] = []
    # Manifest-declared canonical dataset hashes: raw data is not committed, so
    # these cannot be re-hashed here. They are admitted ONLY after the exact
    # string is found physically present in every declared anchor file, each of
    # which is itself a hash-verified source artifact. A fabricated hash cannot
    # pass this: it would have to already exist inside two independent files.
    for entry in repro["dataset"]["canonical_dataset_hashes"]:
        for rel in entry["must_appear_in"]:
            anchor = ROOT / rel
            if not anchor.is_file() or entry["sha256"] not in anchor.read_text(
                encoding="utf-8", errors="replace"
            ):
                failures.append(
                    f"canonical dataset hash not anchored in {rel}: {entry['sha256'][:16]}…"
                )
        known.add(entry["sha256"])
    for sha in git_shas:
        proc = subprocess.run(
            ["git", "cat-file", "-e", f"{sha}^{{commit}}"],
            cwd=ROOT,
            capture_output=True,
            text=True,
        )
        if proc.returncode != 0:
            failures.append(
                f"git object not resolvable (shallow clone? fetch-depth 0 required): {sha[:12]}…"
            )

    occurrences = 0
    unique: set[str] = set()
    abbreviations = 0
    seen_shas = 0
    files = sorted(
        p for p in PACK.rglob("*") if p.is_file() and p.suffix in PACK_SUFFIXES
    )
    for path in files:
        if ".git" in path.parts:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for token in HEX64.findall(text):
            occurrences += 1
            unique.add(token)
            if token not in known:
                failures.append(f"unknown sha256 in {path.relative_to(PACK)}: {token[:16]}…")
        for token in HEX40.findall(text):
            seen_shas += 1
            if token not in allowed_shas:
                failures.append(f"undeclared git sha in {path.relative_to(PACK)}: {token[:12]}…")
        for prefix in ABBR.findall(text):
            abbreviations += 1
            pool = known | allowed_shas
            if not any(value.startswith(prefix) for value in pool):
                failures.append(f"unresolved abbreviation in {path.relative_to(PACK)}: {prefix}…")

    for problem in failures:
        print(f"FAIL {problem}")
    if failures:
        print(f"hashcheck FAILED: {len(failures)} problem(s)")
        return 1
    print(
        f"hashcheck OK: {len(unique)} published sha256 values verified "
        f"({occurrences} occurrences), {seen_shas} full git SHAs printed, "
        f"{abbreviations} abbreviations resolved, "
        f"{len(external)} external git SHAs declared (not locally resolvable)"
    )
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("build", "check", "hashcheck"))
    args = parser.parse_args(argv)
    if args.mode == "build":
        for rel, data in build().items():
            path = PACK / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            print(f"wrote {rel} ({len(data)} bytes)")
        return 0
    if args.mode == "check":
        return check()
    return hashcheck()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
